version: 2

dockerbuild: &dockerbuild
  steps:
    - checkout
    - run:
        name: "Build wheel package"
        command: |
          git submodule update --init
          cd py-pagexml
          ./setup.py bdist_wheel

dockerpublish: &dockerpublish
  steps:
    - run:
        name: "Publish Release on GitHub"
        command: |
          cd py-pagexml
          mkdir artifacts
          mv dist/*.whl artifacts
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./artifacts/

buildfilter: &buildfilter
  filters:
    tags:
      only: /.*/

tagfilter: &tagfilter
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^\d+\.\d+\.\d+$/

jobs:
  build-16.04-py35:
    <<: *dockerbuild
    docker:
      - image: mauvilsa/pagexml:build-ubuntu16.04-py35
  build-18.04-py36:
    <<: *dockerbuild
    docker:
      - image: mauvilsa/pagexml:build-ubuntu18.04-py36
  publish-release-16.04-py35:
    <<: *dockerpublish
    docker:
      - image: mauvilsa/pagexml:build-ubuntu16.04-py35
  publish-release-18.04-py36:
    <<: *dockerpublish
    docker:
      - image: mauvilsa/pagexml:build-ubuntu18.04-py36

workflows:
  version: 2
  main:
    jobs:
      - build-16.04-py35:
          <<: *buildfilter
      - build-18.04-py36:
          <<: *buildfilter
      - publish-release-16.04-py35:
          <<: *tagfilter
          requires:
            - build-16.04-py35
      - publish-release-18.04-py36:
          <<: *tagfilter
          requires:
            - build-18.04-py36
