name: build_test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_24_x86_64:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y swig
      - name: Build wheel files
        run: |
          git submodule update --init py-pagexml/lxml
          cd py-pagexml
          #for ver in cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39; do
          for ver in cp38-cp38; do
            echo "=== Building wheel for $(/opt/python/$ver/bin/python3 --version) ==="
            /opt/python/$ver/bin/pip3 install pkgconfig
            /opt/python/$ver/bin/python3 setup.py bdist_wheel --slim
            auditwheel repair dist/*$ver-linux_x86_64.whl -w dist
            rm dist/*$ver-linux_x86_64.whl
          done
          mv dist ../wheels
      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: wheels
  unittest:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #python: [3.6, 3.7, 3.8, 3.9]
        python: [3.8]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/download-artifact@v2
        with:
          name: wheels
      - name: Install package
        run: |
          find . -type f
          py=$(python3 --version | sed -r 's|Python 3\.([0-9]+)\..*|3\1|')
          pip3 install *-cp$py-*.whl
      - name: Run unit tests
        run: python3 -m pagexml_tests
